-- Создание таблицы hits
CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(500) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hits_timestamp ON hits(timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits(uri);
CREATE INDEX IF NOT EXISTS idx_hits_app ON hits(app);
CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits(ip);
CREATE INDEX IF NOT EXISTS idx_hits_app_uri ON hits(app, uri);
CREATE INDEX IF NOT EXISTS idx_hits_timestamp_app_uri ON hits(timestamp, app, uri);

COMMENT ON TABLE hits IS 'Таблица для хранения статистики посещений эндпоинтов';
COMMENT ON COLUMN hits.id IS 'Уникальный идентификатор записи';
COMMENT ON COLUMN hits.app IS 'Идентификатор сервиса (приложения)';
COMMENT ON COLUMN hits.uri IS 'URI эндпоинта';
COMMENT ON COLUMN hits.ip IS 'IP-адрес пользователя';
COMMENT ON COLUMN hits.timestamp IS 'Время посещения (без временной зоны)';